version: '2'

services:
    app:
        build: .
        volumes:
            - .:/var/www/html
            - ./vhost.conf:/etc/apache2/sites-available/000-default.conf
        ports:
            - 80:80
